spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bankapp
      database: bankapp

server:
  port: 8080

logging:
  level:
    com.revature.bank: DEBUG
    org.springframework.data.mongodb: DEBUG
